name: calculadora_flutter
description: Um novo projeto Flutter de calculadora.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expressions: ^0.2.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
